apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  labels:
    app: phasma
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  labels:
    app: phasma
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database
  labels:
    app: phasma
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cache
  labels:
    app: phasma
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: search
  labels:
    app: phasma
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage
  labels:
    app: phasma
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: broker
  labels:
    app: phasma
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: connect
  labels:
    app: phasma
automountServiceAccountToken: false
